Repository prgrms-be-devcourse/BEDV1_BROONG, pull requests merged in 2021-11, with the labels that each got.

#22 [유지훈] Reservation - 유저별 예약 조회 기능, 특정 시간의 예약 가능 여부 확인 기능, 중복 예약 확인 기능 추가 + 저장 테스트 추가
  build.gradle
  src/main/java/com/prgrms/broong/management/car/converter/CarConverter.java
  src/main/java/com/prgrms/broong/management/domain/converter/ParkCarConverter.java
  src/main/java/com/prgrms/broong/management/dto/ParkCarRequestDto.java
  src/main/java/com/prgrms/broong/management/park/converter/ParkConverter.java
  src/main/java/com/prgrms/broong/reservation/converter/ReservationConverter.java
  src/main/java/com/prgrms/broong/reservation/domain/Reservation.java
  src/main/java/com/prgrms/broong/reservation/dto/ReservationRequestDto.java
  src/main/java/com/prgrms/broong/reservation/dto/ReservationResponseDto.java
  src/main/java/com/prgrms/broong/reservation/repository/ReservationRepository.java
  src/main/java/com/prgrms/broong/reservation/service/ReservationService.java
  src/main/java/com/prgrms/broong/reservation/service/ReservationServiceImpl.java
  src/main/java/com/prgrms/broong/user/convert/UserConverter.java
  src/main/java/com/prgrms/broong/user/domain/User.java
  src/test/java/com/prgrms/broong/reservation/repository/ReservationRepositoryTest.java
  src/test/java/com/prgrms/broong/reservation/service/ReservationServiceTest.java
Labels: 예약, 백엔드

#41 [유지훈] 예약 컨트롤러 구현 및 테스트 추가
  src/main/java/com/prgrms/broong/reservation/controller/ReservationController.java
  src/main/java/com/prgrms/broong/reservation/domain/Reservation.java
  src/main/java/com/prgrms/broong/reservation/dto/ReservationRequestDto.java
  src/main/java/com/prgrms/broong/reservation/service/ReservationService.java
  src/main/java/com/prgrms/broong/reservation/service/ReservationServiceImpl.java
  src/test/java/com/prgrms/broong/reservation/controller/ReservationControllerTest.java
  src/test/java/com/prgrms/broong/reservation/service/ReservationServiceTest.java
Labels: 예약, 백엔드

#57 [유지훈] Reservation 멘토님 피드백 반영 수정
  src/main/java/com/prgrms/broong/reservation/controller/ReservationController.java
  src/main/java/com/prgrms/broong/reservation/converter/ReservationConverter.java
  src/main/java/com/prgrms/broong/reservation/domain/Reservation.java
  src/main/java/com/prgrms/broong/reservation/domain/ReservationStatus.java
  src/main/java/com/prgrms/broong/reservation/dto/ReservationRequestDto.java
  src/main/java/com/prgrms/broong/reservation/dto/ReservationResponseDto.java
  src/main/java/com/prgrms/broong/reservation/repository/ReservationRepository.java
  src/main/java/com/prgrms/broong/reservation/service/ReservationService.java
  src/main/java/com/prgrms/broong/reservation/service/ReservationServiceImpl.java
  src/main/java/com/prgrms/broong/user/dto/UserReservationCheckDto.java
  src/test/java/com/prgrms/broong/reservation/controller/ReservationControllerTest.java
  src/test/java/com/prgrms/broong/reservation/repository/ReservationRepositoryTest.java
  src/test/java/com/prgrms/broong/reservation/service/ReservationServiceTest.java
Labels: 예약, 백엔드

#63 [이범진] - 차, 주차장, 주차장-차 restdocs 오류 해결
  src/docs/asciidoc/api-guide.adoc
  src/main/java/com/prgrms/broong/management/car/domain/Car.java
  src/main/java/com/prgrms/broong/management/domain/ParkCar.java
  src/main/java/com/prgrms/broong/management/park/domain/Park.java
  src/test/java/com/prgrms/broong/management/car/controller/CarControllerTest.java
  src/test/java/com/prgrms/broong/management/car/repository/CarRepositoryTest.java
  src/test/java/com/prgrms/broong/management/controller/ParkCarControllerTest.java
  src/test/java/com/prgrms/broong/management/park/controller/ParkControllerTest.java
  src/test/java/com/prgrms/broong/management/park/repository/ParkRepositoryTest.java
  src/test/java/com/prgrms/broong/management/repository/ParkCarRepositoryTest.java
  src/test/java/com/prgrms/broong/management/service/ParkCarServiceImplTest.java
Labels: 주차장, 버그, 테스트, 차량, 피드백 요청, 백엔드

#64 [유지훈] Reservation Service Page처리 수정 및 ControllerTest - Rest docs 추가
  src/docs/asciidoc/api-guide.adoc
  src/main/java/com/prgrms/broong/reservation/controller/ReservationController.java
  src/main/java/com/prgrms/broong/reservation/service/ReservationService.java
  src/main/java/com/prgrms/broong/reservation/service/ReservationServiceImpl.java
  src/main/java/com/prgrms/broong/user/dto/UserResponseDto.java
  src/test/java/com/prgrms/broong/reservation/controller/ReservationControllerTest.java
  src/test/java/com/prgrms/broong/reservation/repository/ReservationRepositoryTest.java
  src/test/java/com/prgrms/broong/reservation/service/ReservationServiceTest.java
  src/test/java/com/prgrms/broong/user/controller/UserControllerTest.java
Labels: 예약, 버그, 테스트, 피드백 요청, 백엔드

#65 [유지훈] Reservation Scheduling기능 추가
  src/main/java/com/prgrms/broong/BroongApplication.java
  src/main/java/com/prgrms/broong/config/SchedulerConfig.java
  src/main/java/com/prgrms/broong/reservation/domain/ReservationQueue.java
  src/main/java/com/prgrms/broong/reservation/repository/ReservationQueueRepository.java
  src/main/java/com/prgrms/broong/reservation/service/ReservationQueueService.java
  src/main/java/com/prgrms/broong/reservation/service/ReservationQueueServiceImpl.java
  src/main/java/com/prgrms/broong/reservation/service/ReservationServiceImpl.java
  src/main/java/com/prgrms/broong/scheduler/ReservationScheduler.java
Labels: 예약, 피드백 요청, 백엔드
